server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&tinyInt1isBit=false&allowMultiQueries=true&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    password: 123456

  redis:
    #reids单机单实例
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    #redis哨兵模式
#    database: 1
#    password:
#    sentinel:
#      master: test-master
#      nodes: 192.168.0.xxx:26379,192.168.0.xxx:26379,192.168.0.xxx:26379



#MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl